name: Run ScreenDiff Manually

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Test category to run (leave empty to run all, or specify: sot,milo,feds,caas,uar,uar-ai,dc,bacom)'
        required: false
        type: string

jobs:
  test-matrix:
    name: Running ${{ matrix.category }} tests
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            categories: ["sot","milo","feds","caas","uar","uar-ai"]
          - platform: macos-latest
            categories: ["dc","bacom","graybox-bacom","graybox-dc"]
        # If category is specified, create a dynamic matrix
        category: ${{ inputs.category == '' && fromJson(matrix.categories) || fromJson(format('["{}"]', inputs.category)) }}
    runs-on: ${{ matrix.platform }}
    if: ${{ inputs.category == '' || contains(matrix.categories, inputs.category) }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
        
      - name: Run Nala
        run: bash runScreenDiff.sh ${{ matrix.category }}
        shell: bash
        env:
          IMS_EMAIL: ${{ secrets.IMS_EMAIL }}
          IMS_PASS: ${{ secrets.IMS_PASS }}
          HLX_TKN: ${{ secrets.HLX_TKN }}
          SLACK_WH: ${{ secrets.SLACK_WH }}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_ROLE_ARN: ${{secrets.AWS_ROLE_ARN}}
